# -*- coding: utf-8 -*-
"""Untitled5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14k1dSQiME11Xxjui22S4qCjjHy09WKRM
"""

import speech_recognition as sr

def speech_to_text(audio_file):
  r = sr.Recognizer()
  with sr.AudioFile(audio_file) as source:
    audio = r.record(source)
    try:
      text = r.recognize_google(audio)
      return text
    except sr.UnknownValueError:
      return "Speech recognition could not understand audio"

audio_file = "path/to/audio/file.wav"
print(speech_to_text(audio_file))